num1=int(input("Enter the first number:"))
num2=int(input("Enter the second number: "))
print("The addition is :", num1+num2)
print("The subtraction is :", num1-num2)
print("The multiplication is: ", num1*num2)
print("The division is: ", num1/num2)